version: '3.7'
services:
  nginx:
    container_name: cliper_nginx
    build: docker/nginx
    ports:
      - "4000:80"
    volumes:
      - .:/var/www/html/app
    links:
      - php
  php:
    container_name: cliper_php
    build: docker/php
    volumes:
      - .:/var/www/html/app